# Generated by Django 5.2.8 on 2025-11-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_car_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
