# Generated by Django 5.2.8 on 2025-12-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_delete_car_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Member',
        ),
    ]
