# Generated by Django 5.2.8 on 2025-12-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fullname',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(),
        ),
    ]
