# Generated by Django 5.2.8 on 2025-12-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contact_email_alter_contact_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='name',
        ),
    ]
