# Generated by Django 5.2.8 on 2025-11-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('car_photo', models.ImageField(upload_to='cars/%Y/%m/%d/')),
                ('address', models.CharField(max_length=255)),
                ('kilometers_driven', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=100)),
                ('transmission_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
